<?php
$installer = $this;
$installer->startSetup();
// Mega Menu
$installer->addAttribute('catalog_category', 'meigee_cat_ratio', array(
    'group'             => 'Meigee/Enhanced Categories',
    'label'             => 'Ratio',
    'note'              => "<strong style='color:red'>May be used for top-level categories only.</strong><br />Ratio of categories block width to custom content one",
    'type'              => 'varchar',
    'input'             => 'select',
    'source'            => 'Meigee_CategoriesEnhanced/category_attribute_source_block_ratio',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => false,
    'is_html_allowed_on_front'  => false,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'meigee_cat_block_right', array(
    'group'             => 'Meigee/Enhanced Categories',
    'label'             => 'Right Content',
    'note'              => "<strong style='color:red'>May be used for top-level categories only.</strong><br />This content will be shown right after submenu.",
    'type'              => 'text',
    'input'             => 'textarea',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => true,
    'is_html_allowed_on_front'  => true,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'meigee_cat_block_bottom', array(
    'group'             => 'Meigee/Enhanced Categories',
    'label'             => 'Bottom Content',
    'note'              => "<strong style='color:red'>May be used for top-level categories only.</strong><br />This content will be shown under submenu.",
    'type'              => 'text',
    'input'             => 'textarea',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => true,
    'is_html_allowed_on_front'  => true,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'meigee_cat_block_top', array(
    'group'             => 'Meigee/Enhanced Categories',
    'label'             => 'Top Content',
    'note'              => "<strong style='color:red'>May be used for top-level categories only.</strong><br />This content will be shown above submenu.",
    'type'              => 'text',
    'input'             => 'textarea',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => true,
    'is_html_allowed_on_front'  => true,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'meigee_cat_subcontent', array(
    'group'             => 'Meigee/Enhanced Categories',
    'label'             => 'Custom Drop Down Content',
    'note'              => "This content will replace any subcategories. At least one subcategory must be created anyway",
    'type'              => 'text',
    'input'             => 'textarea',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => true,
    'is_html_allowed_on_front'  => true,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'meigee_cat_customlink', array(
    'group'             => 'Meigee/Enhanced Categories',
    'label'             => 'Custom Link',
    'note'              => "1. Use 'http://' to create external link <br /> 2. Use '/' to create link to the home page<br /> 3. Use '#' to disable the link",
    'type'              => 'text',
    'input'             => 'text',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => true,
    'is_html_allowed_on_front'  => true,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'meigee_cat_customlabel', array(
    'group'             => 'Meigee/Enhanced Categories',
    'label'             => 'Category Label',
    'note'              => "",
    'type'              => 'varchar',
    'input'             => 'select',
    'source'            => 'Meigee_CategoriesEnhanced/category_attribute_source_block_labels',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => false,
    'is_html_allowed_on_front'  => false,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));

$installer->addAttribute('catalog_category', 'meigee_cat_labeltext', array(
    'group'             => 'Meigee/Enhanced Categories',
    'label'             => 'Label Text',
    'note'              => "",
    'type'              => 'text',
    'input'             => 'text',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => true,
    'is_html_allowed_on_front'  => true,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'meigee_cat_linktarget', array(
    'group'             => 'Meigee/Enhanced Categories',
    'label'             => 'Link target blank',
    'note'              => 'Choose "Yes" if you want open link in a new tab',
    'type'              => 'varchar',
    'input'             => 'select',
    'source'            => 'Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisablelight',
    'default_value' => 0,
	'sort_order' => 6,
	'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => false,
    'is_html_allowed_on_front'  => false,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'meigee_cat_bg', array(
	 'group'             => 'Meigee/Enhanced Categories',
	 'sort_order'    => 9,
	 'input'         => 'image',
	 'type'          => 'varchar',
	 'label'         => 'Upload your top level category background image',
	 'note'          => 'Will add background image which will be shown as megamenu wrapper. Works only for top level categories.',
	 'backend'       => 'catalog/category_attribute_backend_image',
	 'visible'       => 1,
	 'required'      => 0,
	 'user_defined'  => 1,
	 'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));
$installer->addAttribute('catalog_category', 'meigee_cat_bg_retina', array(
	 'group'             => 'Meigee/Enhanced Categories',
	 'sort_order'    => 10,
	 'input'         => 'image',
	 'type'          => 'varchar',
	 'label'         => 'Upload your top level category Retina background image',
	 'note'          => 'Will add background image which will be shown as megamenu wrapper. Works only for top level categories.',
	 'backend'       => 'catalog/category_attribute_backend_image',
	 'visible'       => 1,
	 'required'      => 0,
	 'user_defined'  => 1,
	 'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));
$installer->addAttribute('catalog_category', 'meigee_cat_bg_option', array(
    'group'             => 'Meigee/Enhanced Categories',
    'label'             => 'Category Background Image Location Option',
    'note'              => 'Set the position for category background image.',
    'type'              => 'varchar',
    'input'             => 'select',
    'source'            => 'Meigee_CategoriesEnhanced/category_attribute_source_block_bg',
    'default_value' => '1',
	'sort_order' => 11,
	'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => false,
    'is_html_allowed_on_front'  => false,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'meigee_cat_menutype', array(
    'group'             => 'Meigee/Enhanced Categories',
    'label'             => 'Top Level Dropdown Menu Type',
    'note'              => "",
    'type'              => 'varchar',
    'input'             => 'select',
    'source'            => 'Meigee_CategoriesEnhanced/category_attribute_source_block_menutype',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => false,
    'is_html_allowed_on_front'  => false,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
	'sort_order' => 0,
));
$installer->addAttribute('catalog_category', 'meigee_cat_max_quantity', array(
    'group'             => 'Meigee/Enhanced Categories',
    'label'             => 'Max. Quantity of categories in 1 row:',
    'note'              => "Set maximum quantity of categories which will be shown in 1 row. If the field will be empty than default value (System -> Configuration -> Categories Enhanced) will be used.",
    'type'              => 'text',
    'input'             => 'text',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => true,
    'is_html_allowed_on_front'  => true,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
	'sort_order' => 0,
));

$installer->endSetup();