<style>
    .apply-popup-btn
    {
        /*position: absolute;*/
        position: fixed;
        right:50px;
        top:50px;
        background-color: #008800;
        padding: 20px;
        width: 50px;
        height: 20px;
    }
    .apply-popup-btn:hover
    {
        background-color: #21a117;
    }
</style>

<div class="apply-popup-btn" id="apply-popup-btn">
    <button onclick="ApplyPopup(); return false;" class="scalable task" type="button" title="<?php echo $this->__('Apply') ?>"><span><span><span><?php echo $this->__('Apply') ?></span></span></span></button>
</div>


<?php if ('list' == $this->getPopupType()) { ?>

    <script type="application/javascript">
        function ApplyPopup()
        {
            window.parent.Windows.close('importConfigPopup');
        }
        var selected_items = JSON.parse('<?php echo Mage::helper('core')->jsonEncode($this->getSelectedItems()) ;  ?>');
        if (window.parent.importSelectedDataItema === false)
        {
            window.parent.importSelectedDataItema = {};
            selected_items.each(function(item)
            {
                window.parent.importSelectedDataItema[item] = true;
            });
        }

//        $$('input.massaction-checkbox').each(function(el)
//        {
//            var is_checked = ('undefined' == window.parent.importSelectedDataItema[el.value]) ? false : window.parent.importSelectedDataItema[el.value];
//            el.checked = is_checked;
//        });
        $$('input.massaction-checkbox').each(function(el)
        {

            var is_checked = ('undefined' == window.parent.importSelectedDataItema[el.value]) ? false : window.parent.importSelectedDataItema[el.value];
            el.checked = is_checked;

            Event.observe(el, 'change', function(element)
            {
                window.parent.importSelectedDataItema[el.value] = el.checked;
            });
        });
        jQuery("#apply-popup-btn").draggable();
    </script>
<?php } elseif ('tree' == $this->getPopupType()) { ?>

    <script type="application/javascript">
        window.dataBaseParams = {};

        function ApplyPopup()
        {
            window.parent.importSelectedDataItema = $('product_categories').value;
            window.parent.Windows.close('importConfigPopup');
        }

        if(window.parent.importSelectedDataItema !== false)
        {
            window.dataBaseParams = {cat_list: window.parent.importSelectedDataItema};
        }

    </script>

<?php } ?>


