<?php
/**
 * @package     compo
 * @copyright   Copyright (c) 2010-2015 MeigeeTeam. (http://www.meigeeteam.com)
 */
 $meigeeOptions = $this->getLayout();
 $lightBox = $meigeeOptions->getMConfigResultByAlias('lightbox_listing');
 $timerStatus = $meigeeOptions->getMConfigResultByAlias('timer_status');
 $timerListingStatus = $meigeeOptions->getMConfigResultByAlias('timer_listing_status');
 $catalogModeWrapper = $meigeeOptions->getMConfigResultByAlias('catalog_mode');
 $catalogMode = $catalogModeWrapper['value']['sv2']['value'];
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="row">
	<div class="widget widget-new-products clearfix">
		<div class="col-xs-12">
			<header class="widget-title">
				<h2><?php echo $this->__('New Products') ?></h2>
			</header>
		</div>
		<div class="widget-products col-xs-12">
			<?php if(!Mage::app()->getLayout()->checkVersion('1.7.x.x')) {
				echo $this->getPagerHtml();
			} ?>
			<div class="row">
				<ul class="products-grid clearfix">
					<?php $i=0; foreach ($_products->getItems() as $_product): ?>
						<li class="item col-sm-3">
							<div class="indent type-1">
								<div class="image-box">
									<?php echo $this->getLayout()->createBlock('page/html')->setProductInfo($_product)->setTemplate('catalog/product/product_labels.phtml')->toHtml(); ?>
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
										<?php
											echo $_product->productHoverImage($this, 420, 'with-mobile', 385);
											$escaped_label = $this->stripTags($_product->getName(), null, true);
											echo '<img '. $_product->getProductMediaResized(420, 'small_image', 'with-mobile', 385)
												->addImageHtmlAttributte('width', 420)
												->addImageHtmlAttributte('alt', $escaped_label)
												->addImageHtmlAttributte('title', $escaped_label)
												->getImageHtmlAttributte().' />';
										?>
									</a>
									<?php if($this->helper('wishlist')->isAllow() || $_compareUrl=$this->getAddToCompareUrl($_product) || $lightBox) { ?>
										<div class="hover-buttons clearfix">
											<div class="toggle-options">
												<i class="meigee-options-vertical"></i>
											</div>
											<div class="options-block">
												<?php if($this->helper('wishlist')->isAllow() || $_compareUrl=$this->getAddToCompareUrl($_product)) { ?>
													<div class="add-to-links">
														<?php if ($this->helper('wishlist')->isAllow()) : ?>
															<span class="link-wishlist-wrapper"><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><i class="meigee-fa-heart"></i></a></span>
														<?php endif; ?>
														<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
															<span class="link-compare-wrapper"><a href="<?php echo $_compareUrl ?>" class="link-compare"><i class="meigee-fa-exchange"></i></a></span>
														<?php endif; ?>
													</div>
												<?php } ?>
												<?php if($lightBox){ ?>
													<a href="<?php echo $_product->getProductMediaResized(930, 'small_image')->getImageSrc(); ?>" class="lightbox-button" data-toggle="lightbox" data-footer="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
														<i class="meigee-magnifier"></i>
													</a>
												<?php } ?>
											</div>
										</div>
									<?php } ?>
								</div>
								<h5 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h5>
								<?php if($_product->isSaleable()): ?>
									<p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
								<?php else: ?>
									<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
								<?php endif; ?>
								<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
								<?php if($timerStatus && $timerListingStatus) {
									echo $this->getLayout()->createBlock('page/html')->setProduct($_product)->setTemplate('catalog/product/listing_timer.phtml')->toHtml();
								} ?>
								<div class="price-action-block two-items<?php echo ($_product->getSpecialPrice() ? ' with-special-price' : ''); ?>">
									<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
									<?php if ($_product->isSaleable()): ?>
										<?php if($catalogMode == 0) { ?>
											<button type="button" title="<?php echo  Mage::helper('core')->quoteEscape($this->__('Add to Cart')); ?>" class="btn btn-default" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="meigee-fa-shopping-cart"></i><span><?php echo $this->__('Add to Cart') ?></span></span></button>
										<?php } ?>
									<?php else: ?>
										<a class="btn btn-default" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo  Mage::helper('core')->quoteEscape($this->__('Read More')); ?>"><span><i class="meigee-eye"></i><span></span><?php echo $this->__('Read More'); ?></span></a>
									<?php endif; ?>
								</div>
							</div>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>
		</div>
	</div>
</div>
<?php endif; ?>
