<div class="comment-block">
<h3><?php echo $this->__('Comment')?></h3>
	<form autocomplete="off">
	    <div class="comment">
	        <div class="comment-form">            
	            <div class="input-box">	                
	                <textarea class="input-text form-control" id="customer_comment" name="customer_comment"></textarea>
	            </div>	            
	        </div>
	    </div>
	</form>
</div>