<?php if ($this->isCustomerLoggedIn()): ?>
    <button type="button" title="<?php echo $this->getButtonTitle() ?>" id="bigone-show-prescription-button"
            class="btn btn-primary type-2"
            onclick="showPrescription(this)"><span><span><?php echo $this->getButtonTitle() ?></span></span>
    </button>
    <script type="text/javascript">
        //<![CDATA[
        document.observe("dom:loaded", bodyOnload);
        function bodyOnload() {
            <?php if (Mage::getSingleton('customer/session')->getQuestion()): ?>
            $('product_addtocart_form').down('#product-addtocart-button').hide();
            $('product_addtocart_form').down('#bigone-show-prescription-button').show();
            <?php else: ?>
            $('product_addtocart_form').down('#product-addtocart-button').show();
            $('product_addtocart_form').down('#bigone-show-prescription-button').hide();
            <?php endif; ?>
        }
        showPrescription = function (button) {
            var questionContainer = button.up('.product-view').down('#question-container');
            if (questionContainer && questionContainer.visible()) {
                questionContainer.hide();
            } else if (questionContainer && !questionContainer.visible()) {
                questionContainer.show();
                Effect.ScrollTo(questionContainer, 1000);
            } else {
                console.warn('The add to cart button was not found');
            }
        };
        //]]>
    </script>
<?php endif; ?>