<?php
$productId = $this->getProduct()->getId();
$helper = Mage::helper('profile');
$brands = $this->getBrandData($productId);
$path = Mage::getBaseUrl('media') .'profile_brand/';
?>
<?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    <?php if ($brands): ?>
        <div id="question-container" style="display: none;">
            <div class="brand-container">
                <input type="hidden" name="profile[brand]" id="profile-brand">
                <input type="hidden" name="profile[profile_cost]" id="profile_cost">
                <div class="title-question"><?php echo $this->__('Q1: Please Choose Brand') ?></div>
                <div class="item-list">
                    <?php if (count($brands)) : ?>
                        <?php foreach ($brands as $brand) : ?>
                            <div class="item-brand" data-id="<?php echo $brand['brand_id'] ?>" id="item-brand-<?php echo $brand['brand_id'] ?>">
                                <img src="<?php echo $path.$brand['logo'] ?> " alt="<?php echo $brand['title'] ?>" 
                                     title="<?php echo $brand['title'] ?>" style="width:250px;height:100px; "/>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </div>
            <div id="profile-loading" style="display:none;">
                <img alt="<?php echo $this->__('Loading...') ?>"
                     src="<?php echo $this->getSkinUrl('images/AjaxLoader.gif') ?>"/>
            </div>
            <div id="profile-container"></div>
            <div id="pres-container" style="display:none"><?php echo $this->getChildHtml('question5') ?></div>
            <div id="bigone-custom-addcartbox" style="margin: 30px; display:none;">
                <div class="quantity-wrapper clearfix">
                    <label for="qty"><?php echo $this->__('Qty:') ?></label>
                    <input readonly type="text" name="profile[qty]" id="qty_custom" maxlength="12" value="1" 
                           title="<?php echo Mage::helper('core')->quoteEscape($this->__('Qty')); ?>" class="form-control qty" />
                </div>
                <button type="button" class="btn btn-primary type-2" 
                        id="bigone-addtocart-btn" title="<?php echo $this->getButtonAddCartTitle() ?>"
                        ><?php echo $this->getButtonAddCartTitle() ?></button>
                <div class="profile-price-box">
                    <?php echo $this->getChildHtml('custom_price')?>
                    <p>Profile Charge: RM<span id="profile-charge">0.00</span></p>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
<script type="text/javascript">
    var $j = jQuery.noConflict();
    var qty_el_cus = document.getElementById('qty_custom');
    var qty_el = document.getElementById('qty');

    $j(document).ready(function () {
        $j('.item-brand').click(function () {
            if ($j('#profile_cost')) $j('#profile_cost').val('0.00');
            if ($j('#pres-container')) $j('#pres-container').hide();
            if ($j('#bigone-custom-addcartbox')) $j('#bigone-custom-addcartbox').hide();
            
            $j('.item-brand').css('border', 'none');
            $j(this).css('border', '3px solid #cc1454');
            var brandId = $j(this).attr('data-id');console.log();
            $j('#profile-brand').val(brandId);
            var post_url = '<?php echo Mage::helper('profile')->getAjaxUrlBrand() ?>';
            new Ajax.Request(
                    post_url,
                    {
                        parameters: {
                            brandId: brandId,
                        },
                        method: 'GET',
                        onLoading: function () {
                            $j('#profile-loading').show();
                        },
                        onSuccess: function (transport) {
                            $j('#profile-loading').hide();
                            var data = transport.responseJSON;
                            $j('#profile-container').html(data.html);
                            if ($j('#glass-container')) {
                                var hash = '#glass-container';
                                $j('#glass-container').fadeIn();
                                $j('html, body').animate({
                                    scrollTop: $j(hash).offset().top
                                }, 800, function(){
                                window.location.hash = hash;
        });
                            }
                        }
                    }
            );
        });
        // custom price box
        var price_box_el = $$('.price-box')[0];
        var price_0 = price_box_el.down('.price');
        var price_1 = price_box_el.down('.price',1);
        var price_custom_el = $$('.profile-price-box')[0];
        
        price_0.on('DOMSubtreeModified',function(){
            console.log(price_0.innerHTML);
            if (price_custom_el) price_custom_el.down('.price').update(price_0.innerHTML);
        });
        if (price_1) {
            price_1.on('DOMSubtreeModified',function(){
                prop = price_1.getAttribute('itemprop');
                if (prop) {
                    console.log(price_1.innerHTML);
                    if (price_custom_el) price_custom_el.down('.price',1).update(price_1.innerHTML);
                }
            });
        }
        
    });
</script>
