<a download href="<?php echo Mage::getBaseUrl('media').'profile/Report_Lokie.xlsx'?>"> Clicking on this link will force download the file</a>
<?php if ($this->checkHasBrand()) : ?>
<div class="profile-container">
    <div class="profile-prescription">
        <div class="question">
            <p style="font-weight: bold">Select method add to cart:</p>
            <input type="radio" name="q-0" value="1" <?php if (Mage::getSingleton('customer/session')->getQuestion() == '1') echo 'checked'; ?>> Prescription<br>
            <input type="radio" name="q-0" value="0" <?php if (Mage::getSingleton('customer/session')->getQuestion() == '0') echo 'checked' ?>> Non-Prescription
        </div>
    </div>
</div>
<script type="text/javascript">
    var $j = jQuery.noConflict();
    $j(document).ready(function () {
        var btn_add_to_cart = $j('#product-addtocart-button');
        var qty_box = $j('.quantity-wrapper');
        var qty_el = $j('#qty');
        var custom_box = $j('#profile-pres-custom');

        $radios = $j("input:radio[name=q-0]");
        if ($radios) {
            var url = '<?php echo Mage::helper('profile')->getAjaxUrlPres() ?>';
            $radios.change(function () {
                var pres = $j(this).val();
                if (pres == '1') {
                    if (custom_box) custom_box.show();
                    if (qty_box) qty_box.hide();
                    if (btn_add_to_cart) btn_add_to_cart.hide();
                    if (qty_el.length) qty_el.val(1); 
                } else {
                    if (custom_box) custom_box.hide();
                    if (qty_box) qty_box.show();
                    if (btn_add_to_cart) btn_add_to_cart.show();
                    if ($j('#question-container')) $j('#question-container').hide();
                }
                new Ajax.Request(
                        url,
                        {
                            parameters: {
                                pres: pres
                            },
                            method: 'GET',
                            onSuccess: function (transport) {
                                var data = transport.responseJSON;
                                console.log(data.pres);
                            }
                        }
                );

            });
        }
    });
</script>
<?php endif;?>