<?php
$helper = Mage::helper('profile');
$brandId = $this->getBrand();
$data = $helper->getDataByBrand($brandId);
?>
<?php if (isset($data['glass'])): ?>
    <div class="info-container" id="glass-container" style="display:none">
        <input type="hidden" name="profile[glass]" id="profile-glass">
        <input type="hidden" name="profile[glass_price]" id="glass_price">
        <div class="title-question"><?php echo $this->__('Q2: Please Choose Glasses') ?></div>
        <div class="item-list">
            <?php
            foreach ($data['glass'] as $glass) :
                $glassId = $glass['glasses_id'];
                ?>
                <div class="item-profile item-glass" id="item-glass-<?php echo $glassId ?>" onclick="changeGlass('<?php echo $glassId ?>')" >
                    <div class="item-info " data-id="<?php echo $glassId ?>">
                        <div class="item-title" >
                            <div class="item-main-title" ><span style="display: inline-block;"><?php echo $glass['title'] ?>
                                <span class="item-tooltip" data-tooltip="<?php echo $glass['tooltip'] ?>">?</span></span>
                            </div>
                            <div><?php echo $glass['subtitle'] ?></div>
                        </div>
                        <div class="item-description"><?php echo $glass['description'] ?></div>
                        <div class="item-price"><?php echo ((int) $glass['price'] != 0) ? '+RM' . $glass['price'] : 'Free' ?></div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
<?php if (isset($data['lens'])): ?>
    <div class="info-container" id="lens-container" style="display:none">
        <input type="hidden" name="profile[lens]" id="profile-lens">
        <input type="hidden" name="profile[lens_price]" id="lens_price">
        <div class="title-question"><?php echo $this->__('Q3: Please Choose Lens') ?></div>
        <div class="item-list">
            <?php
            foreach ($data['lens'] as $len) :
                $lenId = $len['lens_id'];
                ?>
                <div class="item-profile item-len" id="item-len-<?php echo $lenId ?>" onclick="changeLen('<?php echo $lenId ?>')"  >
                    <div class="item-info " data-id="<?php echo $lenId ?>" >
                        <div class="item-title" >
                            <div class="item-main-title" ><span style="display: inline-block;"><?php echo $len['title'] ?>
                                <span class="item-tooltip" data-tooltip="<?php echo $len['tooltip'] ?>">?</span></span>
                            </div>
                            <div><?php echo $len['subtitle'] ?></div>
                        </div>
                        <div class="item-description"><?php echo $len['description'] ?></div>
                        <div class="item-price"><?php echo ((int) $len['price'] != 0) ? '+RM' . $len['price'] : 'Free' ?></div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
<?php if (isset($data['coating'])): ?>
    <div class="info-container" id="coating-container" style="display:none">
        <input type="hidden" name="profile[coating]" id="profile-coating">
        <input type="hidden" name="profile[coating_price]" id="coating_price">
        <div class="title-question"><?php echo $this->__('Q4: Please Choose Coating Add On') ?></div>
        <div class="item-list">
            <?php
            foreach ($data['coating'] as $coating) :
                $coatingId = $coating['coating_id'];
                ?>
                <div class="item-profile item-coating" id="item-coating-<?php echo $coatingId ?>" onclick="changeCoating('<?php echo $coatingId ?>')">
                    <div class="item-info " data-id="<?php echo $coatingId ?>" >
                        <div class="item-title" >
                            <div class="item-main-title" >
                                <span style="display: inline-block;"><?php echo $coating['title'] ?><span class="item-tooltip" data-tooltip="<?php echo $coating['tooltip'] ?>">?</span></span>
                        
                            </div>
                            <div><?php echo $coating['subtitle'] ?></div>
                        </div>
                        <div class="item-description"><?php echo $coating['description'] ?></div>
                        <div class="item-price"><?php echo ((int) $coating['price'] != 0) ? '+RM' . $coating['price'] : 'Free' ?></div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
<script type="text/javascript">
    // change glasses
    var data = <?php echo json_encode($data) ?>;
    var glass_price = 0;
    var lens_price = 0;
    var coating_price = 0;
    var profile_cost = 0;
    var profile_cost_el = $j('#profile_cost');
    function scrollOption(hash) {
        $j('html, body').animate({
            scrollTop: $j(hash).offset().top
        }, 800, function(){
        window.location.hash = hash;
        });
    }
    var hash;
    function changeGlass(glassId) {
        $j('#profile-glass').val(glassId);
        profile_cost -= glass_price;
        glass_price = 0;
        glass_price = parseFloat(data.glass[glassId].price);
        profile_cost += glass_price;
        profile_cost_el.val(profile_cost);
        $j('#profile-charge').html(profile_cost.toFixed(2));
        $j('#glass_price').val(glass_price)
        if ($j('#lens-container').length) {
            $j('#lens-container').fadeIn();
            hash = '#lens-container';
        } else if ($j('#coating-container').length) {    
            $j('#coating-container').fadeIn();
            hash = '#coating-container';
        } else {
            $j('#pres-container').fadeIn();
            if ($j('#bigone-custom-addcartbox').length) {
                $j('#bigone-custom-addcartbox').fadeIn();
            }
            hash = '#pres-container';
        }
        scrollOption(hash);
        $j('.item-glass').css('border', 'none');
        $j('#item-glass-' + glassId).css('border', '3px solid #cc1454');
    }
    function changeLen(lenId) {
        $j('#profile-lens').val(lenId);
        profile_cost -= lens_price;
        lens_price = 0;
        lens_price = parseFloat(data.lens[lenId].price);
        profile_cost += lens_price;
        $j('#lens_price').val(lens_price);
        profile_cost_el.val(profile_cost);
        $j('#profile-charge').html(profile_cost.toFixed(2));
        if ($j('#coating-container').length) {
            $j('#coating-container').fadeIn();
            hash = '#coating-container';
        } else {
            if ($j('#pres-container').length) {
                $j('#pres-container').fadeIn();
            }
            if ($j('#bigone-custom-addcartbox').length) {
                $j('#bigone-custom-addcartbox').fadeIn();
            }
            hash = '#pres-container';
        }
        scrollOption(hash);
        $j('.item-len').css('border', 'none');
        $j('#item-len-' + lenId).css('border', '3px solid #cc1454');
    }
    function changeCoating(coatingId) {
        $j('#profile-coating').val(coatingId);
        profile_cost -= coating_price;
        coating_price = 0;
        coating_price = parseFloat(data.coating[coatingId].price);
        profile_cost += coating_price;
        $j('#coating_price').val(coating_price);
        profile_cost_el.val(profile_cost);
        $j('#profile-charge').html(profile_cost.toFixed(2));
        if ($j('#pres-container').length) {
            $j('#pres-container').fadeIn();
        }
        if ($j('#bigone-custom-addcartbox').length) {
            $j('#bigone-custom-addcartbox').fadeIn();
        }
        $j('.item-coating').css('border', 'none');
        $j('#item-coating-' + coatingId).css('border', '3px solid #cc1454');
        var hash = '#pres-container'
        scrollOption(hash);
    }
</script>
