<?php
$helper = Mage::helper('profile');
$productId = $this->getProductId();
$brandId = $this->getBrand(); //Zend_debug::dump($brandId);
$data = $helper->getDataByBrand($brandId); //Zend_debug::dump($data);
?>
<?php if (isset($data['glass'])): ?>
    <div class="info-container" id="glass-container" style="display:none">
        <input type="hidden" name="profile[glass]" id="profile-glass">
        <div class="title-question"><?php echo $this->__('Q2: Please Choose Glasses') ?></div>
        <div class="item-list">
            <?php
            foreach ($data['glass'] as $glass) :
                $glassId = $glass['glasses_id'];
                ?>
                <div class="item-profile item-glass"  id="item-glass-<?php echo $glassId ?>" onclick="changeGlass('<?php echo $glassId ?>')" >
                    <div class="item-info " data-id="<?php echo $glassId ?>">
                        <div class="item-title"><p><?php echo $glass['title'] ?></p></div>
                        <div class="item-description"><?php echo $len['description'] ?></div>
                        <div class="item-price"><?php echo '+RM' . $glass['price'] ?></div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
<?php if (isset($data['lens'])): ?>
    <div class="info-container" id="lens-container" style="display:none">
        <input type="hidden" name="profile[lens]" id="profile-lens">
        <div class="title-question"><?php echo $this->__('Q3: Please Choose Lens') ?></div>
        <div class="item-list">
            <?php
            foreach ($data['lens'] as $len) :
                $lenId = $len['lens_id'];
                ?>
                <div class="item-profile item-len" id="item-len-<?php echo $lenId ?>" onclick="changeLen('<?php echo $lenId ?>')"  >
                    <div class="item-info " data-id="<?php echo $lenId ?>" >
                        <div class="item-title">
                            <div><?php echo $len['title'] ?></div>
                            <div><?php echo $len['subtitle'] ?></div>
                        </div>
                        <div class="item-description"><?php echo $len['description'] ?></div>
                        <div class="item-price"><?php echo '+RM' . $len['price'] ?></div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
<?php if (isset($data['coating'])): ?>
    <div class="info-container" id="coating-container" style="display:none">
        <input type="hidden" name="profile[coating]" id="profile-coating">
        <div class="title-question"><?php echo $this->__('Q4: Please Choose Coating Add On') ?></div>
        <div class="item-list">
            <?php
            foreach ($data['coating'] as $coating) :
                $coatingId = $coating['coating_id'];
                ?>
                <div class="item-profile item-coating" id="item-coating-<?php echo $coatingId ?>" onclick="changeCoating('<?php echo $coatingId ?>')">
                    <div class="item-info " data-id="<?php echo $coatingId ?>" >
                        <div class="item-title"><?php echo $coating['title'] ?></div>
                        <div class="item-description"><?php echo $len['description'] ?></div>
                        <div class="item-price"><?php echo ($coating['price'] != '0') ? '+RM' . $coating['price'] : 'Free' ?></div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
<script type="text/javascript">
    // change glasses
    function changeGlass(glassId) {
        $j('#profile-glass').val(glassId);
        if ($j('#lens-container')) {
            $j('#lens-container').show();
        } else {
            if ($j('#coating-container')) {
                $j('#lens-container').show();
            }
        }
        console.log('glasId=' + glassId);
        $j('.item-glass').css('border', 'none');
        $j('#item-glass-' + glassId).css('border', '3px solid #cc1454');
    }
    function changeLen(lenId) {
        $j('#profile-lens').val(lenId);
        if ($j('#coating-container')) {
            $j('#coating-container').show();
        }

        console.log('lenId=' + lenId);
        $j('.item-len').css('border', 'none');
        $j('#item-len-' + lenId).css('border', '3px solid #cc1454');
    }
    function changeCoating(coatingId) {
        $j('#profile-coating').val(coatingId);
        if ($j('#pres-container')) {
            $j('#pres-container').show();
        }
        $j('.item-coating').css('border', 'none');
        $j('#item-coating-' + coatingId).css('border', '3px solid #cc1454');
    }
</script>