<?php if ($this->isNewsletterEnabled()): ?>
<ul class="form-list opc-newsletter">
	<li class="control">
		<div class="checkbox">
			<label for="is_subscribed"><input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getCheckByDefault()): ?> checked="checked"<?php endif;?> class="checkbox" /><?php echo $this->__('Sign Up for Newsletter') ?></label>
		</div>
	</li>
</ul>
<?php endif ?>