<?php
/**
 * @package     compo
 * @copyright   Copyright (c) 2010-2015 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<div class="custom-page"><!-- left block starts -->
 <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('custom-pages-left-block')->toHtml(); ?>
<!-- left block ends --> <!-- Right block starts -->
<div class="col-sm-9 rightblock">
<div class="contact-us-content"><!-- Content Starts here -->

<div class="custom-page-main-content">
<div class="page-title">
	<h2><?php echo Mage::helper('contacts')->__('Prescription') ?></h2>
</div>

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('prescription-banner')->toHtml(); ?>

<?php echo $this->getLayout()->createBlock('page/html')->setTemplate('meigee/blockmap_wrapper.phtml')->toHtml(); ?>

<form id="contactForm" class="form-horizontal form-contact" name="simple_contact_form" enctype="multipart/form-data" action="<?php echo $this->getUrl('prescription/') ?>index/sendemail" method="post">
<div style="text-align:center;"><a name="message"></a><div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div></div>
	<div class="panel panel-default">
		
        <div class="form-group">
		<div class="col-md-12">
			<p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
		</div>
	</div>
		<div class="panel-body">
			<ul class="form-list">
				<li class="fields">
					<div class="field form-group">
						<div class="col-md-6">
							<label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Your Name') ?></label>
							<input name="name" id="name" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Name')) ?>" value="<?php echo (Mage::app()->getLayout()->checkVersion('1.7.x.x') ? $this->htmlEscape : $this->escapeHtml).($this->helper('contacts')->getUserName()) ?>" class="form-control required-entry" type="text" />
						</div>
						
					</div>
				</li>
                <li class="form-group">
					<div class="col-md-6">
							<label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Your Email') ?></label>
							<input name="email" id="email" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Email')) ?>" value="<?php echo (Mage::app()->getLayout()->checkVersion('1.7.x.x') ? $this->htmlEscape : $this->escapeHtml).($this->helper('contacts')->getUserEmail()) ?>" class="form-control required-entry validate-email" type="text" />
						</div>
				</li>
				<li class="form-group">
					<div class="col-md-6">
						<label for="telephone"><?php echo Mage::helper('contacts')->__('Contact Number') ?></label>
						<input name="telephone" id="telephone" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Telephone')) ?>" value="" class="form-control" type="text" />
					</div>
				</li>
				<li class="wide form-group">
					<div class="col-md-12">
						<label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Your Message') ?></label>
						<textarea name="comment" id="comment" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Comment')) ?>" class="required-entry form-control" cols="5" rows="9"></textarea>
					</div>
				</li>
                
                <li class="fields">
                <div class="wide">
                    <label for="name" class="required">Upload Your Prescription</label>
                    &nbsp;&nbsp;&nbsp;
                        <input name="MAX_FILE_SIZE" type="hidden" value="2000000" style="width:10px;" />
        <input name="attachment"  type="file" />
                    
                </div>
                
                
                
                
                
               
            </li>
			</ul>
		</div>
	</div>
	
	<div class="buttons-set clearfix">
		<input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
		<button type="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Upload')) ?>" class="btn btn-default pull-left"><span><span><?php echo Mage::helper('contacts')->__('Upload') ?></span></span></button>
	</div>
</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
//]]>
</script>

</div>
<!-- Content Ends here --></div>
</div>
<!-- Right block ends --></div>

