<?php
/**
 * @package     compo
 * @copyright   Copyright (c) 2010-2015 MeigeeTeam. (http://www.meigeeteam.com)
 */

$meigeeOptions = $this->getLayout();
$slider_data_arr = array();
if ($this->getTemplate() == 'widget/slider.phtml')
{
	$slider_data_arr = array('add_to_cart'=>'add_to_cart_slider', 'product_name'=>'product_name_slider', 'price'=>'price_slider', 'compare'=>'compare_slider', 'wishlist'=>'wishlist_slider', 'rating_cust_link'=>'rating_cust_link_slider', 'rating_add_review_link'=>'rating_add_review_link_slider', 'rating_stars'=>'rating_stars_slider', 'stock_status'=>'stock_status_slider', 'desc'=>'desc_slider', 'timer'=>'timer_slider');
}
$visibleProducts = $this->getVisibleProducts();
$visibleProducts = ($visibleProducts > 8 ? 8 : $visibleProducts);
$widgetId = $this->getWidgetId();
$gridType = $this->getCompoGridTemplate();
switch ($gridType) {
	case 1:
		$template = 'widget/grids/default_slider.phtml';
	break;
	case 2:
		$template = 'widget/grids/type_2_slider.phtml';
	break;
	case 3:
		$template = 'widget/grids/type_3_slider.phtml';
	break;
	default:
		$template = 'widget/grids/default_slider.phtml';
	break;
}
?>
<div class="slider-container widget-products">
	<?php
		$collection = $this->getCollection();
		$productCount = count($collection);
		//if($productCount > $visibleProducts) {
		//echo $this->getPager();
		if($productCount > 0) {
	?>
	
		
			
            
            <div class="widget-products-new home-new-product" id="home-slider-<?php echo $widgetId; ?>">
            
			
				<div class="widget-slider products-grid <?php echo 'type-' . $gridType; ?> clearfix owl-carousel owl-theme">
					<?php foreach ($collection as $product): ?>
						<?php
						$widget_tmpl = $this->getLayout()->createBlock('page/html')->setProductInfo($product)->setProductList($this)->setTemplate($template);
						if(!empty($slider_data_arr))
						{
							foreach ($slider_data_arr AS $name=>$data)
							{
								$widget_tmpl->setData($name, $this->getData($data));
							}
						}

						echo $widget_tmpl->toHtml(); ?>
					<?php endforeach ?>
				</div>
				<?php if ($productCount > $visibleProducts): ?>
				<div class="owl-buttons"></div>
				<?php endif; ?>
			</div>
		
	
	<script type="text/javascript">
        jQuery(document).ready(function(){
            jQuery('.widget-products-new .owl-carousel').owlCarousel({
                pagination:false,
                autoPlay:true,
                items:3,
				itemsMobile: [479, 2],
                singleItem:false,
                lazyLoad:true,
                lazyEffect:false,
                addClassActive:true,
                navigation:true,
                navigationText: ['<i class="meigee-arrow-left"></i>','<i class="meigee-arrow-right"></i>']
            });
        });
    </script>
	<?php
		echo $this->getPager();
		} else {
			echo $this->__("Warning: Please make sure you have %s+ products to display in the slider, otherwise widget won't be displayed", $visibleProducts+1);
		}
	?>
</div>
