<?php
/**
 * @package     compo
 * @copyright   Copyright (c) 2010-2015 MeigeeTeam. (http://www.meigeeteam.com)
 */
$meigeeOptions = $this->getLayout();
$contentWidth = $meigeeOptions->getMConfigResultByAlias('responsive');
$contentWidthStatus = $contentWidth['value']['sv3']['value'];
$contentWidthVal = $meigeeOptions->getMConfigResultByAlias('container_width');
/* Font Replacement */
    echo Mage::app()->getLayout()->getBlock('Meigee.customFonts')->_toFontsHtml('Noto+Sans:400,700', true);
    echo Mage::app()->getLayout()->getBlock('Meigee.customFonts')->_toFontsHtml('Rubik:300,400,500,700,900', true);

?>
<?php
if($contentWidthStatus == 1){ ?>
    <style type="text/css">
		body.boxed-header .header-wrapper .container,
		body.boxed-breadcrumbs .breadcrumbs-wrapper .container,
        body.boxed-content .content-wrapper .container,
		body.boxed-footer #footer .container,
        body .container {max-width: <?php echo $contentWidthVal; ?>px; width: 100%;}
    </style>
<?php }
