<?php $posts = $this->getPosts(); ?>
<?php 
$isotope_js = Mage::app()->getLayout()->createBlock('thememanager/widget_products')->includeIsotopeJs();
if ($isotope_js) {
?>
	<script type="text/javascript">
		function grid3Isotope() {
			$container = jQuery('.blog-inner .post-wrapper');
			$container.isotope({
					itemSelector: '.postWrapper',
					resizable: true,
					layoutMode : 'masonry',
					
				});
			}
		jQuery(window).ready(function(){
			var js=document.createElement("script");
			js.setAttribute("type","text/javascript");
			js.setAttribute("src",'<?php echo $isotope_js; ?>');
			js.onload = grid3Isotope;
			document.getElementsByTagName("head")[0].appendChild(js);
		});
	</script>
<?php } ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<div class="blog-wrapper">
<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<div class="blog-inner">
 <ul class="row post-wrapper widget-latest">
    <?php foreach ($posts as $post): ?>
		<li class="item col-sm-4">
			<div class="post-date"><?php echo $post->getCreatedTime(); ?></div>
			<h5><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h5>
			<div class="post-info">
				<p class="post-category">
					<?php
					$postCats = $post->getCats();
					echo Mage::helper('blog')->__('Posted in'); ?>
					<?php foreach ($postCats as $data): ?>
						<a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
					<?php endforeach; ?>
				</p>
				<p class="post-author">
					<?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?>
				</p>
			</div>
			<div class="postContent"><?php echo $post->getPostContent(); ?></div>
			<?php echo $this->getBookmarkHtml($post) ?>
			<div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
			<div class="postDetails">
				<?php if ($this->getCommentsEnabled()): ?>
					<?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" > <?php echo Mage::helper('blog')->__('Comments'); ?></a> |
				<?php endif; ?>
			</div>
			<div class="actions">
				<a title="<?php echo $this->__('Read more') ?>" class="btn btn-default" href="<?php echo $post->getAddress(); ?>"><span><?php echo $this->__('Read') ?></span></a>
			</div>
		</li>
		
		
	<?php endforeach; ?>
</ul>
</div>
</div>