 <?php $posts = $this->getPosts(); ?>
<?php if (count($posts)): ?>
 <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<ul class="row post-wrapper widget-latest blog-category">
    <?php foreach ($posts as $post): ?>
        <li class="item col-sm-4">
            <div class="post-date"><?php echo $post->getCreatedTime(); ?></div>
			<h5><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h5>
			<div class="post-info">
				<p class="post-category">
					<?php
					$postCats = $post->getCats();
					echo Mage::helper('blog')->__('Posted in'); ?>
					<?php foreach ($postCats as $data): ?>
						<a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
					<?php endforeach; ?>
				</p>
				<p class="post-author">
					<?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?>
				</p>
			</div>
            <div class="postContent"><?php echo $post->getPostContent(); ?></div>
            <?php echo $this->getBookmarkHtml($post) ?>
            <div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>
           <div class="postDetails">
				<?php if ($this->getCommentsEnabled()): ?>
					<?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" > <?php echo Mage::helper('blog')->__('Comments'); ?></a>
				<?php endif; ?>
			</div>
        </li>
    <?php endforeach; ?>
</ul>
 <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php else: ?>
    <?php echo Mage::helper('blog')->__('No Posts in this Category.'); ?>
<?php endif; ?>