<?php $post = $this->getPost(); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="postWrapper">
	<div class="postTitle clearfix">
		<h2><?php echo $post->getTitle(); ?></h2>
		<div class="postDetails pull-left">
			<?php $postCats = $post->getCats(); ?>
			<?php if (!empty($postCats)): ?>
				<?php echo Mage::helper('blog')->__('Posted in'); ?>
				<?php foreach ($postCats as $title => $url): ?>
					<a href="<?php echo $url; ?>"><?php echo $title; ?></a>
				<?php endforeach; ?>
			<?php else: ?>
				<?php echo Mage::helper('blog')->__('Posted'); ?>
			<?php endif; ?>
			&nbsp;&nbsp;|&nbsp;&nbsp;
			<?php echo $this->__("By"); ?> <h4 class="poster"><?php echo $post->getUser(); ?></h4>
		</div>
		<small class="pull-right"><?php echo $post->getCreatedTime(); ?></small>
	</div>
	<div class="postContent">
		<?php echo $post->getPostContent(); ?>
	</div>
	<?php echo $this->getBookmarkHtml($post) ?>
	<div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>
</div>

<!-- Comment Section -->

<?php if ($this->getCommentsEnabled()): ?>
    <?php $comments = $this->getComment(); ?>
		<div class="row">
			<div class="col-xs-12">
				<div class="postTitle">
					<a name="commentBox" ></a>
					<h2><?php echo $this->__('Post Comments') ?></h2>
				</div>
			</div>
		</div>
    <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
		<?php $i = 0; foreach ($comments as $comment) : ?>
			<div class="commentWrapper <?php echo $i % 2 == 0 ? 'even' : ''; ?>">
				<div class="commentDetails">
					<h3 class="username">
						<?php echo $comment->getUser(); ?>
					</h3>
					<small><?php echo $this->__("posted on") ?> <?php echo $this->formatDate($comment->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?></small>
				</div>
				<div class="commentContent"><?php echo nl2br($comment->getComment()); ?></div>
			</div>
		<?php $i++; endforeach; ?>
    <?php if ($post->getComments()): ?>
			<div class="postError"><?php echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
    <?php else: ?>
			<?php if ($this->getLoginRequired()): ?>
				<?php if ($this->helper('customer')->isLoggedIn()): ?>
					<form action="" id="postComment" method="post" role="form">
						<fieldset class="group-select">
							<ul class="form-list">
								<li>
									<div class="form-group aw-blog-comment-area">
										<label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label>
										<textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry form-control" rows="10"><?php echo $this->getCommentText(); ?></textarea>
									</div>
									<div class="form-group">
										<p class="required pull-right"><?php echo $this->__('* Required Fields') ?></p>
									</div>
								</li>
							</ul>
						</fieldset>
						<div class="button-set clearfix">
							<input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
							<input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/>
							<input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>
							<button class="btn btn-default" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
						</div>
					</form>
					<script type="text/javascript">
						var contactForm = new VarienForm('postComment', false);
					</script>
				<?php else: ?>
					<p><?php echo Mage::helper('blog')->__('You must be logged in to post a comment.'); ?></p>
					<p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('blog')->__('click here'); ?></a> <?php echo Mage::helper('blog')->__('to log in'); ?></p>
				<?php endif ?>
			<?php else: ?>
				<form action="" id="postComment" method="post" class="form-horizontal">
					<fieldset class="group-select">
						<ul class="form-list">
							<li>
								<div class="form-group">
									<div class="col-sm-6">
										<label for="name" class="required clearfix"><?php echo Mage::helper('blog')->__('Name') ?><em>*</em></label>
										<input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" class="required-entry input-text form-control" type="text" />
									</div>
									<div class="col-sm-6">
										<label for="email" class="required clearfix"><?php echo Mage::helper('blog')->__('Email') ?><em>*</em></label>
										<input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" class="required-entry input-text validate-email form-control" type="text" />
									</div>
								</div>
								<div class="form-group aw-blog-comment-area">
									<div class="col-sm-12">
										<label for="comment" class="required clearfix"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label>
										<textarea name="comment" id="comment" title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry form-control" rows="10"><?php echo $this->getCommentText(); ?></textarea>
									</div>
								</div>
								<div class="form-group">
									<div class="col-sm-12">
										<p class="required pull-right"><?php echo $this->__('* Required Fields') ?></p>
									</div>
								</div>
							</li>
							<?php if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()) { ?>
							<li>
								<?php require_once 'recaptcha/recaptchalib-aw.php';
									// Get a key from http://recaptcha.net/api/getkey
									$publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
									$privatekey = Mage::getStoreConfig('blog/recaptcha/privatekey');
									$error = null;
									echo recaptcha_get_html($publickey, $error);
								?>
							</li>
							<?php } ?>
						</ul>
					</fieldset>
					<div class="button-set clearfix">
						<input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
						<button class="btn btn-default" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
					</div>
				</form>
				<script type="text/javascript">
					var contactForm = new VarienForm('postComment', false);
				</script>
			<?php endif; ?>
    <?php endif; ?>
		<hr class="indent-36 white-space">
<?php endif; ?>