<?php
/**
 * QuickView Button template
 *
 * @see Meigee_AjaxKit_Block_Frontend_QuickView_ListButton
 */
?>


<?php if(!$this->isEnabled()) {   return false; } ?>
<div class="quickview-wrapper">
	<button class="btn-quickview btn btn-primary type-2 <?php echo $this->getClass(); ?>" <?php echo $this->getAttributes(); ?>><span><span><?php echo $this->__('Quick view'); ?></span></span></button>
</div>
