<?php
/**
 * @package     compo
 * @copyright   Copyright (c) 2010-2015 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
$catalogModeWrapper = $this->getLayout()->getMConfigResultByAlias('catalog_mode');
$catalogMode = $catalogModeWrapper['value']['sv2']['value'];
?>
<?php if($this->getItemCount()): ?>
<div class="crosssell-big cart-block">
	<header class="widget-title">
		<h2><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h2>
	</header>
    <ul id="crosssell-products-list" class="clearfix products-grid row">
    <?php
		foreach ($this->getItems() as $_item):
	?>
        <li class="item col-sm-3 clearfix">
            <div class="indent type-1">
    			<div class="image-box">
    				<a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>">
    					<?php
    						$escaped_label = $this->htmlEscape($_item->getName());
    						echo '<img '. $_item->getProductMediaResized(400, 'thumbnail')
    							->addImageHtmlAttributte('alt', $escaped_label)
    							->addImageHtmlAttributte('title', $escaped_label)
    							->getImageHtmlAttributte().' />';
    					?>
    				</a>
    			</div>
                <div class="product-details">
    				<div class="ratings-labels-wrapper">
    					<?php $storeId = Mage::app()->getStore()->getId();
    					$summaryData = Mage::getModel('review/review_summary')->setStoreId($storeId)->load($_item->getId());
    					if ($summaryData['rating_summary']){ ?>
    						<div class="ratings">
    							<?php if ($this->getRatingStars()) : ?>
    								<div class="rating-box">
    									<i class="star">&#9733;</i><i class="star">&#9733;</i><i class="star">&#9733;</i><i class="star">&#9733;</i><i class="star">&#9733;</i>
    									<div class="rating" style="width:<?php echo $summaryData['rating_summary'] ?>%"><i class="star">&#9733;</i><i class="star">&#9733;</i><i class="star">&#9733;</i><i class="star">&#9733;</i><i class="star">&#9733;</i></div>
    								</div>
    							<?php endif; ?>
    						</div>
    					<?php } ?>
    				</div>
                    <h5 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h5>
                    <?php echo $this->getPriceHtml($_item, true) ?>
                    <div class="price-action-block two-items<?php echo ($_item->getSpecialPrice() ? ' with-special-price' : ''); ?>">
                        <?php echo $this->getPriceHtml($_item, true, false) ?>
                        <?php if($catalogMode == 0){ ?>
                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')); ?>" class="btn btn-default" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><i class="meigee-fa-shopping-cart"></i><span><?php echo $this->__('Add to cart'); ?></span></span></button>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </li>
    <?php
		endforeach;
	?>
    </ul>
    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
</div>
<?php endif; ?>
