<style>
	.select-brand {
		float:left;
		width: 150px;
	}
	.profile-list-brand {
		font-size: 16px;
		margin-left: 150px; 
	}
	.profile-brand label {
		text-transform: uppercase;
	}
	.profile-inclue label{font-size: 13px;font-weight: bold}

</style>
<div >
<div class="select-brand"><h4>Selected Brands : <h4></div>
<?php ?>
<?php $brands = $this->getBrands();?>
<?php $productId = Mage::registry('current_product')->getId();?>
<ol class="profile-list-brand">
<?php foreach($brands as $brand) : ?>
	<li class="profile-brand">
		<input type="checkbox" <?php if ($this->isCheckBrand($brand->getId(),$productId)) echo 'checked' ?> value="<?php echo $brand->getId()?>" name="profile_brand[]" />
    	<label><?php echo $brand->getTitle() ?></label>
	</li>
<?php endforeach;?>
</ol>
<div class="profile-inclue">
	<input type="checkbox" <?php if (Mage::helper('profile')->isIncludeTest($productId)) echo 'checked' ?> value="<?php echo 'profile_include' ?>" name="profile_include" />
    <label><?php echo $this->__('Include Eye Test ?') ?></label>
</div>
</div>