<style>
    .pres-new-file {
        display: flex;
        background: #dadee5;
    }
    .file_info {
        padding: 10px;
        font-weight: bold;
    }
    .pres_label{
        background: #988383;
        text-align: center;
        color: #fff;
        height: 30px;
        font-weight: bold;
        font-size: 13px;
        padding: 2px;
    }
    .pres_label label {
        color: #fff;
    }
</style>
<?php
$profileData = $this->getProfiledData();//Zend_debug::dump($profileData);
$pathMedia = Mage::getBaseUrl('media');
$pathSkin = $this->getSkinUrl('profile');
$helper = Mage::helper('profile');
?>
<?php if (!empty($profileData)) : ?>
    <div class="grid">
        <div class="hor-scroll">
            <table cellspacing="0" class="data" id="order_prescription_table">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                </colgroup>
                <thead>
                    <tr class="headings">
                        <!-- <th><span class="profile-title">ID</span></th> -->
                        <th><span class="profile-title">Item</span></th>
                        <th><span class="profile-title">Brand</span></th>
                        <th><span class="profile-title">Glass</span></th>
                        <th><span class="profile-title">Lens</span></th>
                        <th><span class="profile-title">Coating Add On</span></th>
                        <th><span class="profile-title">Prescription Detail</span></th>
                        <th><span class="profile-title">Eye Test</span></th>
                    </tr>
                </thead>
                <tbody>
    <!--                <tr class="even">
                        <td class="empty-text a-center" colspan="8">No records found.</td>
                    </tr>-->
                    <?php foreach ($profileData as $key => $itemData): ?>
                        <?php $logo = (!empty($itemData['brand'])) ? $helper->getLogoBrandById($itemData['brand']) : '' ?>
                        <?php $glassData = (!empty($itemData['glass'])) ? $helper->getDataGlassById($itemData['glass']) : array(); ?>
                        <?php $lensData = (!empty($itemData['lens'])) ? $helper->getDataLensById($itemData['lens']) : array(); ?>
                        <?php $coatingData = (!empty($itemData['coating'])) ? $helper->getDataCoatingById($itemData['coating']) : array(); ?>
                        <tr class="profile-prescription">
                            <td class="item-name"><?php echo Mage::getModel('sales/order_item')->load($key)->getName() ?></td>
                            <td class="profile-logo">
                                <img src="<?php echo $pathMedia.'profile_brand/'.$logo; ?>"
                                     height="100px" width="150px"
                                     />
                            </td>
                            <td class="profile-option">
                                <p>
                                    <?php if (!empty($glassData)): ?>
                                        <?php echo $glassData['title'] . '<br>' ?>
                                        <?php echo $glassData['subtitle'] . '<br>' ?>
                                        <?php echo $helper->formatPrice($glassData['price']) ?>
                                    <?php endif; ?>
                                </p>
                            </td>
                            <td class="profile-option">
                                <p>
                                    <?php if (!empty($lensData)): ?>
                                        <?php echo $lensData['title'] . '<br>' ?>
                                        <?php echo $lensData['subtitle'] . '<br>' ?>
                                        <?php echo $helper->formatPrice($lensData['price']) ?>
                                    <?php endif; ?>
                                </p>
                            </td>
                            <td class="profile-option">
                                <p>
                                    <?php if (!empty($coatingData)): ?>
                                        <?php echo $coatingData['title'] . '<br>' ?>
                                        <?php echo $coatingData['subtitle'] . '<br>' ?>
                                        <?php echo $helper->formatPrice($coatingData['price']) ?>
                                    <?php endif; ?>
                                </p>
                            </td>
                            <td>   
                            <?php if (!empty($itemData['method'])) :?>
                                <p class="profile pres-method"><?php echo $helper->getMethodPresTitle($itemData['method']) ?></p>
                                <?php if ($itemData['method'] == '1' || $itemData['method'] == '3') : ?>
                                    <div class="profile-pres">
                                        <dl>
                                            <dt class="pres-field">Prescription : <?php echo $itemData['p_name'] ?></dt>
                                            <dt class="pres-field">Right</dt> 
                                            <dd>Sphere : <?php echo $itemData['p_right_sph'] ?: 'None' ?></dd>
                                            <dd>Cylinder : <?php echo $itemData['p_right_cyn'] ?: 'None' ?></dd>
                                            <dd>Axis : <?php echo $itemData['p_right_axi'] ?: 'None' ?></dd>
                                            <dd>Near Addition : <?php echo $itemData['p_right_near'] ?: 'None' ?></dd>
                                            <dt class="pres-field">Left</dt>
                                            <dd>Sphere : <?php echo $itemData['p_left_sph'] ?: 'None' ?></dd>
                                            <dd>Cylinder : <?php echo $itemData['p_left_cyn'] ?: 'None' ?></dd>
                                            <dd>Axis : <?php echo $itemData['p_left_axi'] ?: 'None' ?></dd>
                                            <dd>Near Addition : <?php echo $itemData['p_left_near'] ?: 'None' ?></dd>
                                            <?php if(!empty($itemData['pd_number']) && $itemData['pd_number']=='1'):?>
                                                <dt class="pres-field">PD : <?php echo $itemData['p_pd_left'] ?></dt>
                                            <?php elseif ($itemData['pd_number']=='2') :?>
                                                <dt class="pres-field">PD</dt>
                                                <dd>Right : <?php echo $itemData['p_pd_left'] ?: 'None' ?></dd>
                                                <dd>Left : <?php echo $itemData['p_pd_right'] ?: 'None' ?></dd>
                                            <?php endif;?>
                                            <?php if(isset($itemData['p_near'])):?>
                                                <dt class="pres-field">Near PD: <?php echo $itemData['p_near'] ?: 'None' ?></dt>
                                            <?php endif;?>
                                            <dt class="pres-field">Additional Remarks:</dt>
                                            <dd><?php echo $itemData['remark'] ?></dd>
                                        </dl>
                                    </div>
                                <?php endif; ?>
                                <?php if ($itemData['method'] == '2') : ?>
                                    <?php $fileName = $itemData['upload_file']; ?>
                                    <?php $ex = !empty($fileName) ? $helper->getExtensionFile($fileName) : '';
                                        $src = '';
                                    ?>
                                    
                                    <div class="pres-new-file">
                                        <div class="file-logo-box">
                                            <div class="file-logo">
                                            <?php 
                                            if ($helper->isImage($fileName)) {
                                                $src = $pathMedia.'profile/'.$fileName;
                                            } else {
                                                switch ($ex) {
                                                    case 'txt':
                                                        $src = $pathSkin.'/i-docx.png';
                                                        break;
                                                    case 'docx':
                                                        $src = $pathSkin.'/i-docx.png';
                                                        break;
                                                    case 'xlsx':
                                                        $src = $pathSkin.'/i-xlsx.png';
                                                        break;
                                                    case 'pdf':
                                                        $src = $pathSkin.'/i-pdf.png';
                                                        break;
                                                    default:
                                                        break;
                                                }
                                            }
                                            ?>
                                                <img id="file_logo_icon_<?php echo $key?>" src="<?php echo $src?>" width="100px" height="100px"/>
                                            </div>
                                        </div>
                                        <div class="file_info"><span id="pres_filename_<?php echo $key ?>"><?php echo $fileName ?></span></div>
                                    </div>
                                    <div>
                                        <div class="pres_label"><label for="file_upload_<?php echo $key ?>">Choose File To Upload</label></div>
                                        <input type="file" id="file_upload_<?php echo $key ?>" name="file_upload_<?php echo $key?>" style="display: none">
                                    </div>
                                <?php endif; ?>
                                <script type="text/javascript">
                                    var $j = jQuery.noConflict();
                                    var path = '<?php echo $pathMedia.'profile/'?>';
                                    var pathSkin = '<?php echo $this->getSkinUrl('profile').'/' ?>';
                                    var list_img = ['jpg', 'jpeg', 'gif', 'png'];
                                    
                                    $j('#file_upload_<?php echo $key?>').change(function () {
                                        var itemId =  <?php echo $key?>;
                                        var file_data = $j(this).prop('files')[0];
                                        var fileName = file_data.name;
                                        var type = fileName.split('.').pop();
                                        var form_data = new FormData();
                                        form_data.append('file', file_data);
                                        form_data.append('itemId',itemId);
                                        $j.ajax({
                                            url: '<?php echo Mage::getUrl('profile/ajax/editOrder') ?>',
                                            dataType: 'text',
                                            cache: false,
                                            contentType: false,
                                            processData: false,
                                            data: form_data,
                                            method: 'post',
                                            parameters: {
                                                itemId: itemId,
                                            },
                                            success: function () {
                                                console.log('ok');
                                                $j('#pres_filename_'+itemId).text(fileName);
                                                if (list_img.indexOf(type) !== -1) {
                                                    $j("#file_logo_icon_"+itemId).attr("src",path+fileName);
                                                } else {
                                                    switch(type) {
                                                        case 'txt':
                                                            $j("#file_logo_icon_"+itemId).attr("src",pathSkin+'i-docx.png');
                                                            break;
                                                        case 'docx':
                                                            $j("#file_logo_icon_"+itemId).attr("src",pathSkin+'i-docx.png');
                                                            break;
                                                        case 'xlsx':
                                                            $j("#file_logo_icon_"+itemId).attr("src",pathSkin+'i-xlsx.png');
                                                            break;
                                                        case 'pdf':
                                                            $j("#file_logo_icon_"+itemId).attr("src",pathSkin+'i-pdf.png');
                                                            break;
                                                        default:
                                                    }
                                                }
                                            }
                                        });
                                    });
                                </script>
                            <?php endif; ?>
                            </td>
                            <td class="profile-option">
                                <?php if(!empty($itemData['include_test']) && $itemData['include_test']=='1') :?>
                                    <div>Yes</div>
                                <?php else : ?>
                                    <div>No</div>
                                <?php endif?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif; ?>

