<?php
/**
 * @package     compo
 * @copyright   Copyright (c) 2010-2015 MeigeeTeam. (http://www.meigeeteam.com)
 */
 $catalogModeWrapper = $this->getLayout()->getMConfigResultByAlias('catalog_mode');
 $catalogMode = $catalogModeWrapper['value']['sv2']['value'];
 if($catalogMode == 0){
	if(Mage::app()->getLayout()->checkVersion('1.7.x.x')) {
		echo $this->getLayout()->createBlock('core/template')->setTemplate('1.7.x.x/bundle/catalog/product/subprice.phtml')->setThisBlock($this)->toHtml();
	} if(Mage::app()->getLayout()->checkVersion('1.8.0.x')) {
		echo $this->getLayout()->createBlock('core/template')->setTemplate('1.8.0.x/bundle/catalog/product/subprice.phtml')->setThisBlock($this)->toHtml();
	} else {
		echo $this->getLayout()->createBlock('core/template')->setTemplate('bundle/catalog/product/subprice.phtml')->setThisBlock($this)->toHtml();
	}
 }
?>
