<?php
/**
 * @package     compo
 * @copyright   Copyright (c) 2010-2015 MeigeeTeam. (http://www.meigeeteam.com)
 */
	$_product = $this->getProductInfo();
	$product_list = $this->getProductList();
	$_helper = $this->helper('catalog/output');
	$meigeeOptions = $this->getLayout();
	$quickview_wrapper = Mage::app()->getLayout()->getBlock('ajaxkit')->issetSubmodulesConfig('general_add_to_cart');
	$imgSize = $product_list->getImgWidth();
    $widgetId = $product_list->getWidgetId();
	if(!$imgSize){
		$imgSize = 400;
	}
?>
<li class="item">
	<div class="indent type-3">
		<div class="image-box">
			<?php echo $this->getLayout()->createBlock('page/html')->setProductInfo($_product)->setTemplate('catalog/product/product_labels.phtml')->toHtml(); ?>
			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
				<?php
					echo $_product->productHoverImage($this, $imgSize, 'with-mobile', 385);
					// echo $_product->productHoverImage($this, $imgSize);
					$escaped_label = $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true);
					echo '<img '. $_product->getProductMediaResized($imgSize, 'small_image', 'with-mobile', 385)
					// echo '<img '. $_product->getProductMediaResized($imgSize, 'small_image')
						->addImageHtmlAttributte('alt', $escaped_label)
						->addImageHtmlAttributte('width', $imgSize)
						->addImageHtmlAttributte('title', $escaped_label)
						->addImageHtmlAttributte('class', 'lazyOwl')
						// ->addImageHtmlAttributte('class', 'no_ajax_image_loader')
						->addImageHtmlAttributte('data-src', $_product->getProductMediaResized($imgSize, 'small_image')->getImageSrc())
						->getImageHtmlAttributte().' />';
				?>
			</a>
			<?php if(($product_list->getCompoQuickview() && ($quickview_wrapper && isset($quickview_wrapper['enable_quick_view']))) || ($meigeeOptions->getMConfigResultByAlias('lightbox_listing')) || $this->getWishlist() || $this->getCompare()){ ?>
				<div class="hover-buttons clearfix">
					<div class="toggle-options">
						<i class="meigee-options-vertical"></i>
					</div>
					<div class="options-block">
						<?php if($this->getWishlist() || $this->getCompare()) { ?>
							<div class="add-to-links">
								<?php if (($this->helper('wishlist')->isAllow()) && $this->getWishlist()) : ?>
									<span class="link-wishlist-wrapper">
										<a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist'); ?>"><i class="meigee-fa-heart"></i></a>
									</span>
								<?php endif; ?>
								<?php if(($_compareUrl=$product_list->getAddToCompareUrl($_product)) && $this->getCompare()): ?>
									<span class="link-compare-wrapper">
										<a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare'); ?>"><i class="meigee-fa-exchange"></i></a>
									</span>
								<?php endif; ?>
							</div>
						<?php } ?>
						<?php if($product_list->getCompoQuickview() && ($quickview_wrapper && isset($quickview_wrapper['enable_quick_view']))){ ?>
							<?php echo Mage::app()->getLayout()->getBlock('ajaxkit_quick_view_btn')->setProduct($_product)->toHtml(); ?>
						<?php } ?>
						<?php if($meigeeOptions->getMConfigResultByAlias('lightbox_listing')){ ?>
							<a href="<?php echo $_product->getProductMediaResized(500, 'small_image')->getImageSrc();  ?>" class="lightbox-button" data-toggle="lightbox" data-footer="<?php echo $this->stripTags($_product->getName(), null, true) ?>" title="<?php echo $this->__('Lightbox'); ?>">
								<i class="meigee-fa-search-plus" title="<?php echo $this->__('Enlarge'); ?>"></i>
							</a>
						<?php } ?>
					</div>
				</div>
			<?php } ?>
			<div class="product-info">
				<?php if($product_list->getCompoProductCategory()){ ?>
					<h6 class="category-name">
						<?php $categoryIds = $_product->getCategoryIds();
						if(count($categoryIds) ){
							$cat_arr = array();
							foreach($categoryIds as $category){
								$rootId = Mage::app()->getStore()->getRootCategoryId();
								$_category = Mage::getModel('catalog/category')->load($category);
								if ($category != $rootId) {
									$cat_arr[] = $_category->getName();
								}
							}
							echo implode(', ', $cat_arr);
						} ?>
					</h6>
				<?php } ?>
				<?php if($this->getProductName()): ?>
					<h5 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h5>
				<?php endif; ?>
				<?php if($this->getStockStatus()){
					if($_product->isSaleable()): ?>
						<p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
					<?php else: ?>
						<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
					<?php endif;
				} ?>
				<?php $storeId = Mage::app()->getStore()->getId();
					$summaryData = Mage::getModel('review/review_summary')->setStoreId($storeId)->load($_product->getId());
					if ($summaryData['rating_summary']): ?>
					<?php if ($this->getRatingCustLink() || $this->getRatingAddReviewLink() || $this->getRatingStars()) : ?>
						<div class="ratings">
							<?php if ($this->getRatingStars()) : ?>
								<div class="rating-box">
									<i class="star">&#9733;</i><i class="star">&#9733;</i><i class="star">&#9733;</i><i class="star">&#9733;</i><i class="star">&#9733;</i>
									<div class="rating" style="width:<?php echo $summaryData['rating_summary'] ?>%"><i class="star">&#9733;</i><i class="star">&#9733;</i><i class="star">&#9733;</i><i class="star">&#9733;</i><i class="star">&#9733;</i></div>
								</div>
							<?php endif; ?>
							<?php if ($this->getRatingCustLink() || $this->getRatingAddReviewLink()) : ?>
								<p class="rating-links">
									<?php if ($this->getRatingCustLink()) : ?>
										<a href="<?php echo $_product->getProductUrl() ?>#reviews-link"><?php echo $this->__('%d Review(s)', $summaryData['reviews_count']) ?></a>
									<?php endif; ?>
									<?php if ($this->getRatingCustLink() && $this->getRatingAddReviewLink()) : ?>
										<span class="separator">|</span>
									<?php endif; ?>
									<?php if ($this->getRatingAddReviewLink()) : ?>
										<a href="<?php echo $_product->getProductUrl() ?>#reviews-link"><?php echo $this->__('Add Your Review') ?></a>
									<?php endif; ?>
								</p>
							<?php endif; ?>
						</div>
					<?php endif; ?>
				<?php endif; ?>
				<?php if($this->getDesc()){ ?>
					<div class="desc std">
						<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
					</div>
				<?php } ?>
				<?php if($this->getPrice() || $this->getAddToCart()) { ?>
					<div class="price-action-block<?php echo (($this->getAddToCart() && $this->getPrice()) ? ' two-items' : ''); ?><?php echo (($_product->getSpecialPrice() || $this->helper('tax')->getPrice($_product, $_product->getMsrp())) ? ' with-special-price' : ''); ?><?php echo ($_product->getTypeId() === 'bundle' ? ' bundle-type' : ''); ?>">
						<?php if($this->getPrice()):
							 echo  $product_list->getPriceHtml($_product, true, '-widget-'.$widgetId);
						endif; ?>
						<?php if($this->getAddToCart()){ ?>
							<?php if($_product->isSaleable()): ?>
								<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-default btn-cart" onclick="setLocation('<?php echo $product_list->getAddToCartUrl($_product) ?>')"><span><i class="meigee-fa-shopping-cart"></i><span><?php echo $this->__('Add to Cart') ?></span></span></button>
							<?php else: ?>
								<a class="btn btn-default" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->__('Read More'); ?>"><span><i class="meigee-eye"></i><span><?php echo $this->__('Read More'); ?></span></span></a>
							<?php endif; ?>
						<?php } ?>
					</div>
				<?php } ?>
				<?php if($meigeeOptions->getMConfigResultByAlias('timer_status') && $this->getTimer()) {
					echo $this->getLayout()->createBlock('page/html')->setProduct($_product)->setTemplate('catalog/product/listing_timer.phtml')->toHtml();
				} ?>
			</div>
		</div>
	</div>
</li>
