<?php
/**
 * @package     compo
 * @copyright   Copyright (c) 2010-2015 MeigeeTeam. (http://www.meigeeteam.com)
 */
/* @var $this Mage_Catalog_Block_Product_Compare_Sidebar */
?>
<?php
$_helper = $this->helper('catalog/product_compare');
$_items = $_helper->getItemCount() > 0 ? $_helper->getItemCollection() : null;
?>
<?php if ($_items): ?>
	<div class="block block-list block-compare">
		<div class="block-title">
			<strong><span><?php echo $this->__('Compare') ?>
				<?php if($_helper->getItemCount() > 0): ?>
					<small><?php echo $this->__('(%d)', $_helper->getItemCount()) ?></small>
				<?php endif; ?>
			</span></strong>
			<a class="btn btn-default" href="<?php echo $_helper->getClearListUrl() ?>" onclick="return confirm('<?php echo Mage::helper('core')->quoteEscape($this->__('Are you sure you would like to remove all products from your comparison?')); ?>');"><i class="meigee-trash"></i><?php echo $this->__('Clear All') ?></a>
		</div>
		<div class="block-content">
		<?php if($_helper->getItemCount() > 0): ?>
			<ol id="compare-items">
			<?php foreach($_items as $_index => $_item): ?>
			<?php $product = Mage::getModel("catalog/product")->load($_item->getProductId()); ?>
				<li class="item">
					<div class="media-left">
						<a href="<?php echo $this->getProductUrl($product) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>" class="product-image">
							<?php
								$escaped_label = $this->escapeHtml($product->getName());
								echo '<img '. $product->getProductMediaResized(90, 'thumbnail')
									->addImageHtmlAttributte('alt', $escaped_label)
									->addImageHtmlAttributte('title', $escaped_label)
									->addImageHtmlAttributte('class', 'lazyOwl')
									->addImageHtmlAttributte('class', 'no_ajax_image_loader')
									->getImageHtmlAttributte().' />';
							?>
						</a>
					</div>
					<div class="media-body">
						<input type="hidden" class="compare-item-id" value="<?php echo $_item->getId() ?>" />
						<a href="<?php echo $_helper->getRemoveUrl($_item) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove This Item')) ?>" class="btn-remove" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the compare products?') ?>');"><i class="meigee-trash"></i></a>
						<h5 class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a></h5>
						<?php echo $this->getReviewsSummaryHtml($_item) ?>
						<?php echo $this->getPriceHtml($_item, false, '-compare') ?>
					</div>
				</li>
			<?php endforeach; ?>
			</ol>
			<script type="text/javascript">decorateList('compare-items')</script>
			<div class="actions">

				<button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Compare')); ?>" class="btn btn-default" onclick="popWin('<?php echo $_helper->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')"><span><span><i class="meigee-chart"></i><?php echo $this->__('Compare') ?></span></span></button>
			</div>
		<?php else: ?>
			<p class="empty"><?php echo $this->__('You have no items to compare.') ?></p>
		<?php endif; ?>
		</div>
	</div>
<?php endif; ?>
