<?php
/**
 * @package     compo
 * @copyright   Copyright (c) 2010-2015 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<?php
if(count($this->getItemCollection()->getItems())): ?>
<div class="box-collateral box-up-sell">
	<header class="widget-title">
		 <h2><?php echo $this->__('You may also be interested in the following product(s)') ?></h2>
	</header>
    <ul class="products-grid row" id="upsell-product-table">
		<?php $this->resetItemsIterator() ?>
		<?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
			<?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
				<?php if($_link=$this->getIterableItem()): ?>
				<li class="item col-xs-3">
					<div class="indent type-1">
						<div class="image-box">
							<a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo (Mage::app()->getLayout()->checkVersion('1.7.x.x') ? $this->htmlEscape : $this->escapeHtml).($_link->getName()) ?>" class="product-image">
								<?php
									$escaped_label = (Mage::app()->getLayout()->checkVersion('1.7.x.x') ? $this->htmlEscape : $this->escapeHtml).($_link->getName());
									echo '<img '. $_link->getProductMediaResized(294, 'small_image', 'with-mobile', 385)
										->addImageHtmlAttributte('alt', $escaped_label)
										->addImageHtmlAttributte('width', 294)
										->addImageHtmlAttributte('title', $escaped_label)
										->getImageHtmlAttributte().' />';
								?>
							</a>
						</div>
						<h5 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo (Mage::app()->getLayout()->checkVersion('1.7.x.x') ? $this->htmlEscape : $this->escapeHtml).($_link->getName()) ?>"><?php echo (Mage::app()->getLayout()->checkVersion('1.7.x.x') ? $this->htmlEscape : $this->escapeHtml).($_link->getName()) ?></a></h5>
						<?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
						<?php echo $this->getReviewsSummaryHtml($_link) ?>
					</div>
				</li>
				<?php endif; ?>
			<?php endfor; ?>
		<?php endfor; ?>
    </ul>
    <script type="text/javascript">decorateTable('upsell-product-table')</script>
</div>
<?php endif ?>
