<?php
/**
 * @package     compo
 * @copyright   Copyright (c) 2010-2015 MeigeeTeam. (http://www.meigeeteam.com)
 */
/* @var $this Mage_Reports_Block_Product_Compared */
$catalogModeWrapper = $this->getLayout()->getMConfigResultByAlias('catalog_mode');
$catalogMode = $catalogModeWrapper['value']['sv2']['value'];
?>
<?php if ($_products = $this->getRecentlyComparedProducts()): ?>
<h2 class="subtitle"><?php echo $this->__('Your Recently Compared') ?></h2>
<?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_products as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif; ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <div class="indent type-1">
                    <div class="image-box">
                        <a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
        					<?php
        						echo $_product->productHoverImage($this, 800);
        						$escaped_label = $this->stripTags($_product->getName(), null, true);
        						echo '<img '. $_product->getProductMediaResized(800, 'small_image')
        							->addImageHtmlAttributte('alt', $escaped_label)
        							->addImageHtmlAttributte('title', $escaped_label)
        							->getImageHtmlAttributte().' />';
        					?>
        				</a>
                        <?php if($this->helper('wishlist')->isAllow() || $_compareUrl=$this->getAddToCompareUrl($_product)) { ?>
                            <div class="hover-buttons clearfix">
                                <div class="toggle-options">
                                    <i class="meigee-options-vertical"></i>
                                </div>
                                <div class="options-block">
                                    <?php if($this->helper('wishlist')->isAllow() || $_compareUrl=$this->getAddToCompareUrl($_product)) { ?>
                                        <div class="add-to-links">
                                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                <span class="link-wishlist-wrapper"><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><i class="meigee-fa-heart"></i></a></span>
                                            <?php endif; ?>
                                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                                <span class="link-compare-wrapper"><a href="<?php echo $_compareUrl ?>" class="link-compare"><i class="meigee-fa-exchange"></i></a></span>
                                            <?php endif; ?>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                    <h5 class="product-name"><a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h5>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <div class="price-action-block two-items<?php echo ($_product->getSpecialPrice() ? ' with-special-price' : ''); ?>">
                        <?php echo $this->getPriceHtml($_product, true, '-widget-compared-grid') ?>
                        <?php if ($_product->isSaleable()): ?>
                            <?php if($catalogMode == 0) { ?>
                            <button type="button" title="<?php echo  Mage::helper('core')->quoteEscape($this->__('Add to Cart')); ?>" class="btn btn-default" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="meigee-fa-shopping-cart"></i><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php } ?>
                        <?php else: ?>
                            <a class="btn btn-default" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo  Mage::helper('core')->quoteEscape($this->__('Read More')); ?>"><span><i class="meigee-eye"></i><span></span><?php echo $this->__('Read More'); ?></span></a>
                        <?php endif; ?>
                    </div>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==count($_products)): ?>
        </ul>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
