<!-- <div class="a-center">
	<button class="btn btn-default show_form" onclick="return false;" data-form-name="form_login_html" style="display:none;"><span><span><?php echo $this->__('Login') ?></span></span></button>
	<button class="btn btn-default show_form" onclick="return false;" data-form-name="form_register_html"><span><span><?php echo $this->__('Register') ?></span></span></button>
	<button class="btn btn-default show_form" onclick="return false;" data-form-name="form_forgot_password_html"><span><span><?php echo $this->__('Forgot Password') ?></span></span></button>
</div> -->